### ISSUE TITLE
Attempt to invoke interface method 'boolean android.widget.MediaController' Exception when I tried to add MediaController

### ISSUE THREAD

**Issue by chilupa** [aizhang/Android-VideoView#2]
So glad that I finally found a solution here for using your optimized VideoView in my app. 

I'm trying to add `MediaController `to the **VideoView** so that my users can have a control over the Video in my customized `MessageAdapter ` but I'm getting this exception. How do i resolve this? Can you please guide me. 

```
E: FATAL EXCEPTION: main Process: com.apvolution.bcmadmin, PID: 28109
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.widget.MediaController$MediaPlayerControl.canPause()'
on a null object reference
at android.widget.MediaController.disableUnsupportedButtons(MediaController.java: 323)
at android.widget.MediaController.setEnabled(MediaController.java: 635)
at com.apvolution.bcmadmin.adapter.VideoView$3.onPrepared(VideoView.java: 476)
at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java: 2871)
at android.os.Handler.dispatchMessage(Handler.java: 102)
at android.os.Looper.loop(Looper.java: 154)
at android.app.ActivityThread.main(ActivityThread.java: 6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 757)
```

**Comment by aman811** [comment]
@chilupa @aizhang  any solution? I am facing the same error.

java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.widget.MediaController$MediaPlayerControl.canPause()' on a null object reference
                                                                          at android.widget.MediaController.disableUnsupportedButtons(MediaController.java:323)
                                                                          at android.widget.MediaController.show(MediaController.java:362)
                                                                          at android.widget.MediaController.show(MediaController.java:314)

**Comment by KyThuat1-TLTVietNam** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
mmagian, @nschlemm, @zaicheng-qi, @jorandradefig, @krinoid, @quangnd-pgvn, @lak, @Chufyjj, @pellejacobs, @vladyslavstartsev, @njm2112, @talaatmagdyx, @cxq1992, @dagumak, @liuzz1983, @taudep, @hardiksurana, @ShanshanLi-Scarlett, @svenhornberg, @scalp42

**Comment by guijunchen** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
koalasleeping, @ysnows, @thisdad, @jzaicn, @powermobileweb, @breakliu, @jon-imagine, @bombond, @Jason0107, @Angel-fund, @monmorn, @litei, @caixudong1223, @LiLiaoBin, @liuqingsong1528, @indrajitsinh, @justinchou, @zhangwx8973, @Colincl, @periler

**Comment by Ererere911** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
swordencao, @bubble501, @snogrammer, @serejandmyself, @dvasiliauskas, @akuma, @txssseal, @rokhimin, @arturoaviles, @iceycode, @XL19860214, @wiraperdana, @tameeshB, @jotadepaula, @bonjouribrahim, @nvtiendung, @gnepud, @jballesterosc, @willwangcc, @p3k
